### ISSUE TITLE
Binary release

### ISSUE THREAD

**Issue by JabberwockPL** [MrPnut/SCXI#1]
Would it be possible to include the binary release? Thanks!

**Comment by MrPnut** [comment]
Hi @JabberwockPL 

I went ahead and published a release.  Let me know if you have any issues.

Thanks!

**Comment by JabberwockPL** [comment]
It works OK!

One issue that I have (beside the one you mentioned, i.e. key reports) is that the left touch area requires a press, while the right does not. This makes it difficult to program in a game, as both D-pad direction and a button press are recorded at the same time.

**Comment by MrPnut** [comment]
Gotcha,

I will take a look at this.

Thanks

**Comment by MrPnut** [comment]
@JabberwockPL 

Please see https://github.com/MrPnut/SCXI/releases/tag/v1.0.1 to see if this works better for you.

Thanks
