### ISSUE TITLE
Cant Compile

### ISSUE THREAD

**Issue by icortezsendo** [MrPnut/SCXI#2]
Hello!,
I'm a programmer but i don't know anything about .net. I install sdk 3 and 5 i think, but i get the next error when i try to compile. (i am from Chile so some things are in spanish):

C:\Users\USUARIO\Downloads\SCXI-master>dotnet build
Microsoft (R) Build Engine versión 16.11.2+f32259642 para .NET
Copyright (C) Microsoft Corporation. Todos los derechos reservados.

  Determinando los proyectos que se van a restaurar...
C:\Users\USUARIO\Downloads\SCXI-master\SCXI\SCXI.csproj : warning NU1603: SCXI depende de Device.Net (>= 3.1.1), pero no se encontró Device.Net 3.1.1. Se resolvió una mejor coincidencia aproximada de Device.Net 4.0.0. [C:\Users\USUARIO\Downloads\SCXI-master\SCXI.sln]
C:\Users\USUARIO\Downloads\SCXI-master\SCXI\SCXI.csproj : warning NU1603: SCXI depende de Hid.Net (>= 3.1.1), pero no se encontró Hid.Net 3.1.1. Se resolvió una mejor coincidencia aproximada de Hid.Net 4.0.0. [C:\Users\USUARIO\Downloads\SCXI-master\SCXI.sln]
  Todos los proyectos están actualizados para la restauración.
  SCXI.SteamController -> C:\Users\USUARIO\Downloads\SCXI-master\SCXI.SteamController\bin\Debug\netstandard2.0\SCXI.SteamController.dll
C:\Users\USUARIO\Downloads\SCXI-master\SCXI\SCXI.csproj : warning NU1603: SCXI depende de Device.Net (>= 3.1.1), pero no se encontró Device.Net 3.1.1. Se resolvió una mejor coincidencia aproximada de Device.Net 4.0.0.
C:\Users\USUARIO\Downloads\SCXI-master\SCXI\SCXI.csproj : warning NU1603: SCXI depende de Hid.Net (>= 3.1.1), pero no se encontró Hid.Net 3.1.1. Se resolvió una mejor coincidencia aproximada de Hid.Net 4.0.0.
C:\Users\USUARIO\Downloads\SCXI-master\SCXI\FeatureEnforcer.cs(17,26): **error** CS0246: El nombre del tipo o del espacio de nombres 'WindowsHidDevice' no se encontró (¿falta una directiva using o una referencia de ensamblado?) [C:\Users\USUARIO\Downloads\SCXI-master\SCXI\SCXI.csproj]
C:\Users\USUARIO\Downloads\SCXI-master\SCXI\FeatureEnforcer.cs(21,34): **error** CS0246: El nombre del tipo o del espacio de nombres 'WindowsHidDevice' no se encontró (¿falta una directiva using o una referencia de ensamblado?) [C:\Users\USUARIO\Downloads\SCXI-master\SCXI\SCXI.csproj]

ERROR al compilar.

C:\Users\USUARIO\Downloads\SCXI-master\SCXI\SCXI.csproj : warning NU1603: SCXI depende de Device.Net (>= 3.1.1), pero no se encontró Device.Net 3.1.1. Se resolvió una mejor coincidencia aproximada de Device.Net 4.0.0. [C:\Users\USUARIO\Downloads\SCXI-master\SCXI.sln]
C:\Users\USUARIO\Downloads\SCXI-master\SCXI\SCXI.csproj : warning NU1603: SCXI depende de Hid.Net (>= 3.1.1), pero no se encontró Hid.Net 3.1.1. Se resolvió una mejor coincidencia aproximada de Hid.Net 4.0.0. [C:\Users\USUARIO\Downloads\SCXI-master\SCXI.sln]
C:\Users\USUARIO\Downloads\SCXI-master\SCXI\SCXI.csproj : warning NU1603: SCXI depende de Device.Net (>= 3.1.1), pero no se encontró Device.Net 3.1.1. Se resolvió una mejor coincidencia aproximada de Device.Net 4.0.0.
C:\Users\USUARIO\Downloads\SCXI-master\SCXI\SCXI.csproj : warning NU1603: SCXI depende de Hid.Net (>= 3.1.1), pero no se encontró Hid.Net 3.1.1. Se resolvió una mejor coincidencia aproximada de Hid.Net 4.0.0.
C:\Users\USUARIO\Downloads\SCXI-master\SCXI\FeatureEnforcer.cs(17,26): error CS0246: El nombre del tipo o del espacio de nombres 'WindowsHidDevice' no se encontró (¿falta una directiva using o una referencia de ensamblado?) [C:\Users\USUARIO\Downloads\SCXI-master\SCXI\SCXI.csproj]
C:\Users\USUARIO\Downloads\SCXI-master\SCXI\FeatureEnforcer.cs(21,34): error CS0246: El nombre del tipo o del espacio de nombres 'WindowsHidDevice' no se encontró (¿falta una directiva using o una referencia de ensamblado?) [C:\Users\USUARIO\Downloads\SCXI-master\SCXI\SCXI.csproj]
    4 Advertencia(s)
    2 Errores

Tiempo transcurrido 00:00:01.24

C:\Users\USUARIO\Downloads\SCXI-master>dotnet run
No se ha podido encontrar un proyecto para ejecutar. Asegúrese de que exista uno en C:\Users\USUARIO\Downloads\SCXI-master o pase la ruta de acceso al proyecto mediante --project.

**Comment by MrPnut** [comment]
Hi @icortezsendo!

My fault.  I made some changes to Hid.NET to support setting feature reports.  I did not make this change for all the platforms that Hid.NET supports, so I have my own fork of it.  I forgot to publish the .nupkg.

The packages should be able to restore correctly now.  I ran a build on pipelines just to make sure, and it builds fine: https://github.com/MrPnut/SCXI/runs/4199577373

Let me know if you have any more issues!

Thanks
